### ISSUE TITLE
Describe "vernac" in README

### ISSUE THREAD

**Issue by AJFaraday** [betacraft/ruby-vernac#1]
The README for this repo appears to be unchanged from the Ruby repo. It would be good to include a section on the vernacular functionality:
- what is it?/why it's being done.
- where are the vernacular terms defined?
- any additional configuration required.

**Comment by aniketawati** [comment]
This fork is not being maintained. I have edited the Readme to reflect the status, and links to relevant repos/projects.

**Comment by AJFaraday** [comment]
That makes much more sense, totally happy to call this issue closed. :)
